project:
  type: website
  resources:
    - google348074bdd9084810.html
    - robots.txt

website:
  title: "CBRC"
  open-graph:
    site-name: "Caltech Bioinformatics Resource Center"
  site-url: "https://caltech-bioinformatics-resource-center.github.io/"
  navbar:
    background: light
    right:
      - text: "Who We Are"
        href: about.qmd
      - text: "Tutorials"
        href: https://caltech-bioinformatics-resource-center.github.io/Tutorials/
      - text: "Contact Us"
        href: contact.qmd
  page-footer:
      left: |
        <img src="black_Caltech_logo.png" alt="CBRC logo" class="footer-logo">
      right: |
        © 2025 Caltech Bioinformatics Resource Center
  search: false

format:
  html:
    theme: flatly
    css: styles.css
    toc: false
markdown:
  html: true






