project:
  type: website

website:
  title: "CBRC"
  navbar:
    background: light
    right:
      - text: "Who We Are"
        href: about.qmd
      - text: "Tutorials"
        href: https://pachterlab.github.io/cbrc-spec/
      - text: "Contact Us"
        href: contact.qmd
  page-footer:
      left: |
        <img src="black_Caltech_logo.png" alt="CBRC logo" class="footer-logo">
      right: |
        © 2025 Caltech Bioinformatics Research Center
  search: false

format:
  html:
    theme: flatly
    css: styles.css
    toc: false
markdown:
  html: true






